--- 
addons: 
  apt: 
    packages: 
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libgstrtspserver-1.0-dev
    update: true
before_install: 
  - "cargo install cross"
  - "sudo systemctl start docker"
cache: cargo
dist: bionic
env: 
  - TARGET=build
  - TARGET=test
jobs: 
  - 
    env: "CARGO_CMD=\"cargo\" TARGET=\"x86_64-pc-linux-gnu\""
    name: "stock cargo"
  - 
    env: "CARGO_CMD=\"cross\" TARGET=\"armv7-unknown-linux-gnueabihf\""
    name: "cross cargo"
language: rust
rust: 
  - stable
script: 
  - "./ci/build.sh"
