--- 
addons: 
  apt: 
    packages: 
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libgstrtspserver-1.0-dev
    update: true
cache: cargo
dist: bionic
env:
  global:
    - DOCKER=docker
jobs: 
  - 
    env: "CARGO=\"cargo\" TARGET=\"x86_64-unknown-linux-gnu\""
  - 
    env: "CARGO=\"cross\" TARGET=\"armv7-unknown-linux-gnueabihf\""
language: rust
rust: 
  - stable
script: 
  - "TASK=build ./ci/build.sh"
  - "TASK=test ./ci/build.sh"
