--- 
addons: 
  apt: 
    packages: 
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libgstrtspserver-1.0-dev
    update: true
arch:
  - amd64 
  - arm64 # while this technically isn't the RPi4 it's a nice proof of concept 
cache: cargo
dist: bionic
language: rust
os: linux
rust: 
  - stable
