name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install apt dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update -yq
        sudo apt-get -yq --no-install-suggests --no-install-recommends install \
        libgstreamer1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-plugins-ugly \
        gstreamer1.0-libav \
        libgstrtspserver-1.0-dev
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings # -Wall -Werror
